# Generated by Django 5.2 on 2026-09-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='digist',
            new_name='digest',
        ),
    ]
